### ISSUE TITLE
Materials appear to ignore custom front-matter properties in Fabricator partials

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/fabricator#18]
Hoping @lyzadanger or @erikjung can help with this one, because I'm apparently not smart enough to figure it out on my own!

As of #17 being merged, there's a placeholder style for external documentation links, which can be really useful when passing along patterns that borrow from some standard or existing body of work:

![screen shot 2015-05-07 at 5 10 40 pm](https://cloud.githubusercontent.com/assets/69633/7528396/02486b7e-f4dc-11e4-871e-4eb8aa1d49ab.png)

My intention was to allow for documentation links to be passed along similar to other attributes like `notes`:

``` html

---
notes: |
  These are notes associated with this `button` component.
see:
  SUITCSS Documentation: https://github.com/suitcss/components-button/
  MDN Documentation: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

---
<button class="button">Submit</button>
```

But after much banging my head against the wall, I discovered that, for whatever reason, I can't get materials to output _any_ custom YAML properties. Even this:

``` html

---
foo: 'bar'

---
<p>foo {{ foo }}</p>
```

Will compile to:

``` html
<p>foo </p>
```

I whipped up a quick `JSON.stringify` helper for Handlebars, and none of my custom properties are actually making it to the template.

Help? :helicopter: 

**Update:** The simplified examples above do not reflect that this is impacting Fabricator partials specifically. Please read the whole thread for an elaborated description of the issue.

**Comment by erikjung** [comment]
Looking at [what's happening](https://github.com/fbrctr/fabricator-assemble/blob/master/index.js#L329-L340) in Fabricator Assemble, it appears that any _custom_ front-matter is available at `{{material-name.field}}`, so in this case you would use:

``` hbs
{{button.foo}}
```

EDIT: though looking at the test fixtures, it seems like the namespace shouldn't be required.

Example: https://github.com/fbrctr/fabricator-assemble/blob/master/test/fixtures/materials/components/alerts/primary.html

**Comment by lyzadanger** [comment]
My guess is that @erikjung 's comment gives some meat to the matter but I'm happy to help if it doesn't get you all the way, @tylersticka

**Comment by tylersticka** [comment]
@lyzadanger @erikjung That example (as well as the material name) is useful when you're in an actual material template, but it's less useful when you're in a Fabricator partial, in this case `f-item-content.html`. That's the context I can't find documented, and it's essential to being able to implement new features without hacking `fabricator-assemble`.

So, I'm still stumped.

**Comment by lyzadanger** [comment]
@tylersticka I'll take this one!

**Comment by tylersticka** [comment]
Thank you!

**Comment by erikjung** [comment]
@tylersticka As a temporary workaround, you can try `{{@root.button.foo}}`, if you need to develop something and don't mind seeing the button specific data showing up on every material.

**Comment by tylersticka** [comment]
@erikjung Thanks, but I think I'll just hold off for now. The hard part (the styles and markup) is done, wiring it in _should_ be trivial. I'd rather just postpone the task for now.

**Comment by erikjung** [comment]
We created an issue for this in the Fabricator Assemble repo. https://github.com/fbrctr/fabricator-assemble/issues/9

**Comment by tylersticka** [comment]
Thanks, guys!

**Comment by tylersticka** [comment]
I have confirmed that this is working as of #22 being merged. :+1:
