### ISSUE TITLE
Running `gulp` without `--dev` flag fails to build fabricator CSS

### ISSUE THREAD

**Issue by lyzadanger** [cloudfour/fabricator#20]
If you run, say:

`gulp` and then `gulp serve`

`f.css` won't get built (part of `styles:fabricator` task). There's something going on in that task that fails if `!dev`.

**Comment by erikjung** [comment]
After looking into this a bit, it appears to be due to CSSO failing on the Fabricator styles (but not on the Toolkit). Per discussing with @lyzadanger, we're going to remove CSSO from the build process for now.

**Comment by erikjung** [comment]
I'll let @lyzadanger verify and close this.
