### ISSUE TITLE
Simplify mapping of template helpers

### ISSUE THREAD

**Issue by erikjung** [cloudfour/fabricator#4]
Currently, template helpers must be specified individually as properties of an object passed along to the assembly function call.

``` js
// assemble
gulp.task('assemble', function (done) {
    assemble({
        // apply additional helpers
        helpers: {
            ifEqual: require('./build/helpers/ifEqual')
        }
    });
    done();
});
```

 It would be preferable to not have to update the Gulp task each time a new template helper is created.

**Comment by lyzadanger** [comment]
I think your PR fixes this.
