### ISSUE TITLE
Write helper to create "pretty names" for patterns

### ISSUE THREAD

**Issue by lyzadanger** [cloudfour/fabricator#6]
To make fabricator emulate custom ordering with prettier presented names, we need to make a helper and provide it to the `assemble` task.

This helper should regexp the `name` attribute of the pattern in a similar fashion to what we did on VSE, stripping patterns off the front that match `/[0-9]{1,4}\-?/`. Ish.

**Comment by erikjung** [comment]
This may be addressed by https://github.com/cloudfour/fabricator/pull/7

**Comment by lyzadanger** [comment]
Yup.
