### ISSUE TITLE
Proposed Strategy

### ISSUE THREAD

**Issue by lyzadanger** [cloudfour/fabricator#8]
Hi @erikjung @lharding @tylersticka !

I'm going to stop futzing with our fork of fabricator for the nonce. Here's my summary: I did not find anything we couldn't accomplish with relative ease using fabricator.

I haven't opted to complete out the entire feature list just now, but have identified ways to complete those outstanding features with minimal fuss. e.g. "ability to display build time/date" should be easy to accomplish with a Handlebars helper and `moment.js`.

The system seems flexible, and, frankly, I keep having moments of "oh, this is exactly how I would have done it anyway." There are a few things that don't feel intuitively perfect to me, like the directory structure and some naming (e.g. `views`) but they're either easy to fix or not show-stoppers to me.

What I'd like to propose:
- We commit to using fabricator, our fork, in a pilot way for the cloudfour-dot-com work (or not, but the following steps assume it)
- We plan to complete out the rest of the core features next week. We could actually start using it for cloudfour-dot-com work _before_ that as long as we fork _again_ to wherever that work happens so we can pull in upstream. Or we could complete the full feature set before using on cloudfour-dot-com. I'm not fussed.
- We make every attempt _not_ to modify/fork `fabricator-assemble`. That means a small amount of acceptance for some opinionated stuff. Most relevant is that it uses `lib-sass` for CSS that styles the surrounding UI. 

Thoughts?

**Comment by erikjung** [comment]
Plan makes sense to me. I agree that tweaking has been pretty straightforward so far. I am curious about one proposition though:

> We make every attempt not to modify/fork fabricator-assemble. That means a small amount of acceptance for some opinionated stuff. Most relevant is that it uses lib-sass for CSS that styles the surrounding UI.

How come? Do we intend to maintain some level of compatibility with the original fork? I don't see a way to remedy some of the aforementioned annoynances (the directory structure and hard-coded naming of _views_, for example) without tweaking this file.

**Comment by tylersticka** [comment]
The schedule and overall plan-of-attack sounds reasonable to me. Based on our timeline for visual design, we probably won't get started on using this tool until the week after next, so forking it ahead of time is probably unnecessary.

**Comment by lyzadanger** [comment]
@erikjung It feels "wrong" to me—I'd like to keep the modularity of `fabricator-assemble` intact. I'm not totally sold on having a local version of it in the codebase, as we lose out on any upstream changes. I think we should try to have a minimum footprint of stuff we "own" and maintain.

**Comment by erikjung** [comment]
@lyzadanger For addressing the feature list, can we agree to the process of:
1. Choose something to work on.
2. Create a self-assigned issue to identify the soon-to-be-work-in-progress.
3. Create a new branch, for all or just part of the issue work.
4. PR the branch and reference the original issue.
5. Close original issue when applicable.

**Comment by lyzadanger** [comment]
Yup.

**Comment by lyzadanger** [comment]
As I am investigating #11 and doing a full diff between our `dev` branch and upstream fabricator, I'm coming to have some opinions. Most relevantly, I am starting to think that our fork of fabricator may most naturally be our own, a potentially dead-end fork, and that that is fine. What we're really leaning on is `fabricator-assemble`. The fabricator repo itself is a collection of skeleton starting points and (somewhat opinionated) build tasks and assets. As long as, at the end of the day, one of the `gulp` tasks correctly invokes `assemble`, there's minimal dependencies between the two repositories (fabricator and fabricator-assemble). Having said that, there's not a _total_ disconnect, so we'll need to keep that in mind. `webpack` is a good example. 

What's my point here?

It's that I'm feeling less clenched about making changes to our fork of fabricator that preclude easily merging in upstream changes. I'm also feeling like that, aside from some larger gulp refactor I'm considering, we've made few material changes to the structure of the repository.

**Comment by erikjung** [comment]
@lyzadanger If that means we might be touching Fabricator-assemble, here's that starting point branch I mentioned before that has only the most minimal changes needed to relocate the module to a local directory. 

https://github.com/cloudfour/fabricator/compare/dev...cloudfour:feature-local-assembler

**Comment by lyzadanger** [comment]
@erikjung I still don't think we'd touch `fabricator-assemble`. That's part of my point :). `fabricator` vis-a-vis this fork becomes "ours" and we maintain it. We never touch `fabricator-assemble` if we can avoid it.
